name: Check PR Labels

on:
  pull_request:
    types:
      - opened
      - labeled
      - unlabeled

jobs:
  check_labels:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "do-not-merge" label
        if: contains(github.event.pull_request.labels.*.name, 'do-not-merge')
        run: |
          echo "This PR should not be merged."
          exit 1
